import "./style/header.css";
import { Inter } from "next/font/google";
import logo from "./images/home/logo.png"

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header>
          <div className="header-image">
            <img src={logo} alt="Imagen de l pagina" />
          </div>
          <div className="header-container-buttons">
            <div className="container-buttons-center">
              <input type="submit" />
              <input type="submit" />
            </div>
          </div>
          <div className="header-searchbar">
            <input type="text" />
          </div>
        </header>
        {children}
      </body>
    </html>
  );
}
